version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - python blog.py build

  post_build:
    commands:
      - bash ./deploy.sh

artifacts:
  base-directory: build
  files: '**/*'
