version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - apt-get update && apt-get install -y jpegoptim npm
      - npm install -g html-minifier

  build:
    commands:
      - python blog.py build
      - find build -name *.jpg -exec jpegoptim -m85 {} \;
      - find build -name *.jpg -exec mogrify -verbose -resize 2048x2048 {} \;
      - find build -name *.html -exec html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype {} -o {} \;

  post_build:
    commands:
      - bash ./deploy.sh

artifacts:
  base-directory: build
  files: '**/*'
