name: deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          version: "latest"
      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Lint with Ruff
        run: uv run ruff check .

      - name: Build
        run: uv run python blog.py build

      - name: Deploy to S3
        run: |
          aws s3 sync ./build/ s3://sandwichnews.org --exclude "*.jpg" --cache-control max-age=900
          aws s3 sync ./build/ s3://sandwichnews.org --include "*.jpg" --cache-control max-age=7200

      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id E12B42DU84I3C --paths '/*'
